### ISSUE TITLE
Can not install Poetry on Ubuntu 20.04

### ISSUE THREAD

**Issue by voronind** [python-poetry/install.python-poetry.org#103]
Python 3.8

```console
$ curl -sSL https://install.python-poetry.org | python3 -

Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/.../.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.3.1): Creating environment
Poetry installation failed.
See /home/.../projects/poetry-installer-error-333ykixc.log for error logs.
```

```console
$ cat /home/.../projects/poetry-installer-error-333ykixc.log

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/poetry-installerowd8qj5i/virtualenv.pyz/__main__.py", line 167, in <module>
  File "/tmp/poetry-installerowd8qj5i/virtualenv.pyz/__main__.py", line 163, in run
  File "/tmp/poetry-installerowd8qj5i/virtualenv.pyz/virtualenv/__main__.py", line 16, in run
  File "/tmp/poetry-installerowd8qj5i/virtualenv.pyz/virtualenv/run/__init__.py", line 28, in cli_run
  File "/tmp/poetry-installerowd8qj5i/virtualenv.pyz/virtualenv/run/__init__.py", line 46, in session_via_cli
  File "/tmp/poetry-installerowd8qj5i/virtualenv.pyz/virtualenv/run/__init__.py", line 74, in build_parser
  File "/tmp/poetry-installerowd8qj5i/virtualenv.pyz/virtualenv/run/plugin/activators.py", line 11, in __init__
  File "/tmp/poetry-installerowd8qj5i/virtualenv.pyz/virtualenv/run/plugin/base.py", line 44, in options
  File "/tmp/poetry-installerowd8qj5i/virtualenv.pyz/virtualenv/run/plugin/base.py", line 23, in entry_points_for
  File "/tmp/poetry-installerowd8qj5i/virtualenv.pyz/virtualenv/run/plugin/base.py", line 23, in <genexpr>
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'virtualenv.activation.xonsh'

Traceback:

  File "<stdin>", line 919, in main
  File "<stdin>", line 550, in run
  File "<stdin>", line 571, in install
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "<stdin>", line 643, in make_env
  File "<stdin>", line 629, in make_env
  File "<stdin>", line 333, in make
  File "<stdin>", line 357, in run
```

**Comment by casesolved-co-uk** [comment]
I got a similar error:

```
# curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/root/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (2.3.2): Creating environment
Poetry installation failed.
See /opt/poetry-installer-error-k2dx__lu.log for error logs.
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/poetry-installer4qz6a_ar/virtualenv.pyz/__main__.py", line 178, in <module>
  File "/tmp/poetry-installer4qz6a_ar/virtualenv.pyz/__main__.py", line 174, in run
  File "/tmp/poetry-installer4qz6a_ar/virtualenv.pyz/virtualenv/__main__.py", line 21, in run
  File "/tmp/poetry-installer4qz6a_ar/virtualenv.pyz/virtualenv/run/__init__.py", line 42, in cli_run
  File "/tmp/poetry-installer4qz6a_ar/virtualenv.pyz/virtualenv/run/__init__.py", line 66, in session_via_cli
  File "/tmp/poetry-installer4qz6a_ar/virtualenv.pyz/virtualenv/run/__init__.py", line 100, in build_parser
  File "/tmp/poetry-installer4qz6a_ar/virtualenv.pyz/virtualenv/run/plugin/creators.py", line 24, in __init__
  File "/tmp/poetry-installer4qz6a_ar/virtualenv.pyz/virtualenv/run/plugin/creators.py", line 31, in for_interpreter
  File "/tmp/poetry-installer4qz6a_ar/virtualenv.pyz/virtualenv/run/plugin/base.py", line 39, in options
  File "/tmp/poetry-installer4qz6a_ar/virtualenv.pyz/virtualenv/run/plugin/base.py", line 18, in entry_points_for
  File "/tmp/poetry-installer4qz6a_ar/virtualenv.pyz/virtualenv/run/plugin/base.py", line 18, in <genexpr>
  File "/usr/lib/python3.8/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsFramework'

Traceback:

  File "<stdin>", line 937, in main
  File "<stdin>", line 574, in run
  File "<stdin>", line 595, in install
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "<stdin>", line 667, in make_env
  File "<stdin>", line 653, in make_env
  File "<stdin>", line 355, in make
  File "<stdin>", line 379, in run
```
