### ISSUE TITLE
Installer not working MacOS 13.3

### ISSUE THREAD

**Issue by rjalexa** [python-poetry/install.python-poetry.org#114]
Not able to install poetry with the official installer on a Macbook Pro M2 with MacOS 13.3 using python 3.10.11 (pyenv installed).

```
bob@RJA16 ~ % curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/Users/bob/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.4.2): Creating environment
Traceback (most recent call last):
  File "<stdin>", line 945, in <module>
  File "<stdin>", line 923, in main
  File "<stdin>", line 560, in run
  File "<stdin>", line 581, in install
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "<stdin>", line 653, in make_env
  File "<stdin>", line 639, in make_env
  File "<stdin>", line 317, in make
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/venv/__init__.py", line 66, in __init__
    self.symlinks = should_use_symlinks(symlinks)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/venv/__init__.py", line 31, in should_use_symlinks
    raise Exception("This build of python cannot create venvs without using symlinks")
Exception: This build of python cannot create venvs without using symlinks
```

**Comment by dimbleby** [comment]
please search for duplicates, and then close this

**Comment by rjalexa** [comment]
Thanks. Not always easy to find duplicates (depending on which terms you use).

This solved my problem https://github.com/python-poetry/install.python-poetry.org/issues/52#issuecomment-1419111826

Installed python 3.9 with pyenv and all was good.
