### ISSUE TITLE
Add poetry to `winget` for Windows installation

### ISSUE THREAD

**Issue by alexchandel** [python-poetry/install.python-poetry.org#129]
Please add poetry to the [winget](https://github.com/microsoft/winget-cli) package manager.

Currently, installing poetry requires pasting an install script into a powershell Window, and possibly manually modifying the PATH.  This is inconvenient at best, and difficult to guide another person to do.  `winget` is Microsoft's open source package manager and already has thousands of packages, including all versions of Python.

**Comment by alexchandel** [comment]
Impossible-to-debug issues that others have include:

```
PS C:\windows\system32> (Invoke-WebRequest -Uri https://install.python-poetry.org/ -UseBasicParsing).Content | py -      Retrieving Poetry metadata
Traceback (most recent call last):
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1041, in _send_output
    self.send(msg)
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 979, in send
    self.connect()
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1458, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 945, in <module>
  File "<stdin>", line 923, in main
  File "<stdin>", line 524, in run
  File "<stdin>", line 786, in get_version
  File "<stdin>", line 847, in _get
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shivam.vedant\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>
```

How is the average user to know how to debug this?  And this is the primary supported installation method!

**Comment by devmcp** [comment]
This would be great. Currently the most straightforward path seems to be to install scoop so we can install pipx so we can install poetry.

Is a winget installer to install poetry more directly feasible or likely in the near term?

**Comment by alexchandel** [comment]
A year later, Poetry is going to become unused abandonware because its installation method is so horrible.

**Comment by vikhik** [comment]
One of the reasons I can't support poetry for our teams is because installation can't be easily automated/taken care of.

It's a big blocker for us.
