### ISSUE TITLE
install-poetry.py fails on Python 3.10.3

### ISSUE THREAD

**Issue by mortenlj** [python-poetry/install.python-poetry.org#62]
- [N/A] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [N/A] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 21.10
- **Poetry version**: N/A
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

When trying to install Poetry on Python 3.10.3 (built from source), a weird exception happens when the subprocess module is imported, which doesn't happen if I start an interpreter and import subprocess.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/subprocess.py", line 69, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.10/ensurepip/__init__.py", line 4, in <module>
    import subprocess
  File "/usr/local/lib/python3.10/subprocess.py", line 74, in <module>
    import _posixsubprocess
ModuleNotFoundError: No module named '_posixsubprocess'

Traceback:

  File "/tmp/./install-poetry.py", line 879, in main
    return installer.run()
  File "/tmp/./install-poetry.py", line 517, in run
    raise PoetryInstallationError(
```

The problem doesn't happen when running with Python 3.9.11.

**Comment by neersighted** [comment]
Hello, @ubotser -- it is unclear what you are asking or what is happening from the message you posted. I can only assume you ran into some issue in your code you are asking for help with -- please use appropriate channels like Discussions or Discord, and spell out your problem (what do you expect, what happens instead) plus background details (OS version, Python version, etc).
